# Generated by Django 4.1 on 2022-08-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='No message', max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
