# Generated by Django 4.1 on 2022-09-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings1', models.CharField(max_length=1000)),
                ('greetings2', models.CharField(max_length=1000)),
                ('greetings3', models.CharField(max_length=1000)),
                ('slogan', models.CharField(max_length=1500)),
            ],
        ),
    ]
