# Generated by Django 4.1 on 2022-09-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_indexcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexcontent',
            name='slogan',
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='slogan1',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='slogan2',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='slogan3',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
