# Generated by Django 4.1 on 2022-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_indexcontent_slogan_indexcontent_slogan1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcontent',
            name='slidesThemeName',
            field=models.CharField(default='Regular', max_length=300),
        ),
    ]
